# Generated by Django 6.0.1 on 2026-03-05 10:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=[
                        "ALTER TABLE notifications ADD COLUMN attempts integer NOT NULL DEFAULT 0;",
                        "ALTER TABLE notifications ADD COLUMN last_error text NOT NULL DEFAULT '';",
                        "ALTER TABLE notifications ADD COLUMN scheduled_for datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;",
                        "ALTER TABLE notifications ADD COLUMN sent_at datetime NULL;",
                        "ALTER TABLE notifications ADD COLUMN status varchar(32) NOT NULL DEFAULT 'pending';",
                        "CREATE INDEX IF NOT EXISTS notificatio_recipie_e77cb9_idx ON notifications (recipient_id, status, scheduled_for);",
                        "CREATE INDEX IF NOT EXISTS notifications_sent_at_idx ON notifications (sent_at);",
                    ],
                    reverse_sql=migrations.RunSQL.noop,
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="notification",
                    name="attempts",
                    field=models.PositiveIntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="notification",
                    name="last_error",
                    field=models.TextField(blank=True, default=""),
                ),
                migrations.AddField(
                    model_name="notification",
                    name="scheduled_for",
                    field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                migrations.AddField(
                    model_name="notification",
                    name="sent_at",
                    field=models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                migrations.AddField(
                    model_name="notification",
                    name="status",
                    field=models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=32,
                    ),
                ),
                migrations.AddIndex(
                    model_name="notification",
                    index=models.Index(
                        fields=["recipient", "status", "scheduled_for"],
                        name="notificatio_recipie_e77cb9_idx",
                    ),
                ),
            ],
        ),
        migrations.RunSQL(
            sql=[
                "UPDATE notifications SET status = 'sent', sent_at = COALESCE(sent_at, created_at), scheduled_for = COALESCE(scheduled_for, created_at);",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name="notification",
            name="scheduled_for",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="notification",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
    ]
