# Generated by Django 6.0.1 on 2026-03-05 10:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification_delivery_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(max_length=64, unique=True)),
                ('enabled_by_default', models.BooleanField(default=True)),
                ('default_repeat_minutes', models.PositiveIntegerField(default=15)),
                ('default_watch_scope', models.CharField(choices=[('own', 'Own'), ('team', 'Team'), ('all', 'All')], default='own', max_length=16)),
                ('apply_to_teamleaders', models.BooleanField(default=False)),
                ('apply_to_admins', models.BooleanField(default=False)),
                ('apply_to_superusers', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_policies',
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('repeat_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('watch_scope', models.CharField(blank=True, choices=[('own', 'Own'), ('team', 'Team'), ('all', 'All')], max_length=16, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'ordering': ['event_type', 'user_id'],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_type'), name='uniq_notification_preference_user_event')],
            },
        ),
    ]
