# Generated by Django 6.0.1 on 2026-03-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_notification_channel"),
        ("notifications", "0006_move_user_facing_models"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.DeleteModel(name="NotificationPreference"),
                migrations.DeleteModel(name="NotificationPolicy"),
                migrations.DeleteModel(name="Notification"),
            ],
        ),
    ]
