# Generated by Django 6.0.1 on 2026-01-27 09:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='partners.partner')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='partners.partnersource')),
            ],
            options={
                'db_table': 'leads',
                'indexes': [models.Index(fields=['partner', 'received_at'], name='leads_partner_b721a5_idx'), models.Index(fields=['partner', 'source', 'received_at'], name='leads_partner_a9eec6_idx'), models.Index(fields=['partner', 'external_id'], name='leads_partner_558987_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('partner', 'external_id'), name='uniq_partner_external_id_notnull')],
            },
        ),
    ]
