# Generated by Django 6.0.1 on 2026-02-03 11:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=100)),
                ('color', models.CharField(default='#6B7280', max_length=16)),
                ('is_default_for_new_leads', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_terminal', models.BooleanField(default=False)),
                ('counts_for_conversion', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'lead_statuses',
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.leadstatus'),
        ),
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lead_pipelines',
                'indexes': [models.Index(fields=['is_default', 'is_active'], name='lead_pipeli_is_defa_29d7b1_idx')],
            },
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='pipeline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='statuses', to='leads.pipeline'),
        ),
        migrations.AddField(
            model_name='lead',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='leads', to='leads.pipeline'),
        ),
        migrations.CreateModel(
            name='LeadStatusAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted')], max_length=64)),
                ('source', models.CharField(choices=[('api', 'API'), ('admin', 'Admin'), ('system', 'System'), ('import', 'Import')], default='api', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('payload_before', models.JSONField(blank=True, null=True)),
                ('payload_after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_audit_events', to=settings.AUTH_USER_MODEL)),
                ('from_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_from_status_events', to='leads.leadstatus')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_audit_logs', to='leads.lead')),
                ('to_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_to_status_events', to='leads.leadstatus')),
            ],
            options={
                'db_table': 'lead_status_audit_logs',
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='lead_status_event_t_6d16cf_idx'), models.Index(fields=['lead', 'created_at'], name='lead_status_lead_id_01f6c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LeadStatusTransition',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('requires_comment', models.BooleanField(default=False)),
                ('from_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transitions', to='leads.leadstatus')),
                ('to_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transitions', to='leads.leadstatus')),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transitions', to='leads.pipeline')),
            ],
            options={
                'db_table': 'lead_status_transitions',
                'indexes': [models.Index(fields=['pipeline', 'is_active'], name='lead_status_pipelin_77d18b_idx'), models.Index(fields=['from_status', 'to_status'], name='lead_status_from_st_ae23a0_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pipeline', 'from_status', 'to_status'), name='uniq_status_transition_alive'), models.CheckConstraint(condition=models.Q(('from_status', models.F('to_status')), _negated=True), name='check_transition_not_self')],
            },
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['pipeline', 'order'], name='lead_status_pipelin_d5c8e5_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['pipeline', 'is_active'], name='lead_status_pipelin_999135_idx'),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('pipeline', 'code'), name='uniq_status_code_per_pipeline_alive'),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_new_leads', True), ('is_deleted', False)), fields=('pipeline',), name='uniq_default_status_per_pipeline_alive'),
        ),
    ]
