# Generated by Django 6.0.1 on 2026-02-03 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_leadstatus_lead_status_pipeline_leadstatus_pipeline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadStatusIdempotencyKey',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(choices=[('change_status', 'Change Status'), ('bulk_change_status', 'Bulk Change Status')], max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveSmallIntegerField(default=0)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_status_idempotency_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_status_idempotency_keys',
                'indexes': [models.Index(fields=['endpoint', 'created_at'], name='lead_status_endpoin_02d8f0_idx'), models.Index(fields=['actor_user', 'created_at'], name='lead_status_actor_u_031d9a_idx')],
                'constraints': [models.UniqueConstraint(fields=('actor_user', 'endpoint', 'key'), name='uniq_lead_status_idempotency_per_user_endpoint_key')],
            },
        ),
    ]
