# Generated by Django 6.0.1 on 2026-02-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_lead_manager_lead_leads_manager_4420ff_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatusidempotencykey',
            name='endpoint',
            field=models.CharField(choices=[('change_status', 'Change Status'), ('bulk_change_status', 'Bulk Change Status'), ('assign_manager', 'Assign Manager'), ('bulk_assign_manager', 'Bulk Assign Manager'), ('unassign_manager', 'Unassign Manager'), ('bulk_unassign_manager', 'Bulk Unassign Manager')], max_length=64),
        ),
    ]
