# Generated by Django 6.0.1 on 2026-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_alter_leadstatusidempotencykey_endpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadstatusauditlog',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned')], max_length=64),
        ),
    ]
