# Generated by Django 6.0.1 on 2026-02-03 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_alter_leadstatusauditlog_event_type'),
        ('partners', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadComment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lead_comments',
            },
        ),
        migrations.RemoveField(
            model_name='lead',
            name='payload',
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_leads', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='lead',
            name='expected_revenue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_duplicate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_contacted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_contact_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='lead',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(10, 'Low'), (20, 'Normal'), (30, 'High'), (40, 'Urgent')], default=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='product',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_content',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_medium',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='utm_term',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['partner', 'phone'], name='leads_partner_c18186_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['partner', 'email'], name='leads_partner_ee9a10_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['partner', 'priority', 'received_at'], name='leads_partner_07d264_idx'),
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.CheckConstraint(condition=models.Q(('expected_revenue__isnull', True), ('expected_revenue__gte', 0), _connector='OR'), name='check_lead_expected_revenue_non_negative'),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadcomment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='leads.lead'),
        ),
        migrations.AddIndex(
            model_name='leadcomment',
            index=models.Index(fields=['lead', 'created_at'], name='lead_commen_lead_id_5d4f58_idx'),
        ),
        migrations.AddIndex(
            model_name='leadcomment',
            index=models.Index(fields=['author', 'created_at'], name='lead_commen_author__8b584b_idx'),
        ),
    ]
