# Generated by Django 6.0.1 on 2026-02-04 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_leadcomment_remove_lead_payload_lead_assigned_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadcomment',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
