# Generated by Django 6.0.1 on 2026-02-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_leadcomment_is_pinned'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadDuplicateAttempt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('external_id', models.CharField(blank=True, default='', max_length=128)),
                ('phone', models.CharField(blank=True, db_index=True, default='', max_length=32)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('existing_lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_attempts', to='leads.lead')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_duplicate_attempts', to='partners.partner')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_duplicate_attempts', to='partners.partnersource')),
            ],
            options={
                'db_table': 'lead_duplicate_attempts',
                'indexes': [models.Index(fields=['partner', 'phone', 'created_at'], name='lead_duplic_partner_617071_idx'), models.Index(fields=['existing_lead', 'created_at'], name='lead_duplic_existin_ed58bd_idx')],
            },
        ),
    ]
