# Generated by Django 6.0.1 on 2026-02-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0009_leadduplicateattempt"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="duplicate_of",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="is_duplicate",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="utm_campaign",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="utm_content",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="utm_medium",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="utm_source",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="utm_term",
        ),
        migrations.RemoveField(
            model_name="leadduplicateattempt",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="leadduplicateattempt",
            name="payload",
        ),
        migrations.AddField(
            model_name="leadduplicateattempt",
            name="email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AlterField(
            model_name="leadduplicateattempt",
            name="phone",
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
