# Generated by Django 6.0.1 on 2026-02-18 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_remove_lead_utm_and_duplicate_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='check_lead_expected_revenue_non_negative',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='expected_revenue',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='product',
        ),
    ]
