# Generated by Django 6.0.1 on 2026-02-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_remove_lead_check_lead_expected_revenue_non_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='geo',
            field=models.CharField(blank=True, db_index=True, default='', max_length=2),
        ),
    ]
