# Generated by Django 6.0.1 on 2026-02-18 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_leadcomment_deleted_at_leadcomment_is_deleted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_soft_deleted', 'Lead Soft Deleted'), ('lead_restored', 'Lead Restored'), ('lead_hard_deleted', 'Lead Hard Deleted'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_soft_deleted', 'Comment Soft Deleted'), ('comment_restored', 'Comment Restored'), ('comment_pinned', 'Comment Pinned'), ('comment_unpinned', 'Comment Unpinned'), ('duplicate_rejected', 'Duplicate Rejected')], max_length=64)),
                ('entity_type', models.CharField(choices=[('lead', 'Lead'), ('lead_status', 'Lead Status'), ('lead_comment', 'Lead Comment'), ('duplicate_attempt', 'Duplicate Attempt')], default='lead', max_length=32)),
                ('entity_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('source', models.CharField(choices=[('api', 'API'), ('admin', 'Admin'), ('system', 'System'), ('import', 'Import')], default='api', max_length=32)),
                ('reason', models.TextField(blank=True, default='')),
                ('batch_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload_before', models.JSONField(blank=True, null=True)),
                ('payload_after', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'lead_audit_logs',
            },
        ),
        migrations.RemoveIndex(
            model_name='leadstatusauditlog',
            name='lead_status_event_t_6d16cf_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadstatusauditlog',
            name='lead_status_lead_id_01f6c2_idx',
        ),
        migrations.AddField(
            model_name='leadauditlog',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_status_audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadauditlog',
            name='from_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_from_status_events', to='leads.leadstatus'),
        ),
        migrations.AddField(
            model_name='leadauditlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_audit_logs', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='leadauditlog',
            name='to_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_to_status_events', to='leads.leadstatus'),
        ),
        migrations.RemoveField(
            model_name='leadstatusauditlog',
            name='actor_user',
        ),
        migrations.RemoveField(
            model_name='leadstatusauditlog',
            name='from_status',
        ),
        migrations.RemoveField(
            model_name='leadstatusauditlog',
            name='lead',
        ),
        migrations.RemoveField(
            model_name='leadstatusauditlog',
            name='to_status',
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['event_type', 'created_at'], name='lead_audit__event_t_9b460d_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['lead', 'created_at'], name='lead_audit__lead_id_c544e3_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['entity_type', 'created_at'], name='lead_audit__entity__503ed7_idx'),
        ),
        migrations.AddIndex(
            model_name='leadauditlog',
            index=models.Index(fields=['batch_id', 'created_at'], name='lead_audit__batch_i_52fdad_idx'),
        ),
        migrations.DeleteModel(
            name='LeadStatusAuditLog',
        ),
    ]
