# Generated by Django 6.0.1 on 2026-02-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_conversion_and_sales(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    LeadStatus = apps.get_model("leads", "LeadStatus")
    User = apps.get_model("iam", "User")

    LeadStatus.objects.filter(is_terminal=True, counts_for_conversion=True).update(conversion_bucket="WON")
    LeadStatus.objects.filter(is_terminal=True, counts_for_conversion=False).update(conversion_bucket="LOST")
    LeadStatus.objects.filter(is_terminal=False).update(conversion_bucket="IGNORE")

    manager_ids = set(User.objects.filter(role="MANAGER").values_list("id", flat=True))
    for lead in Lead.objects.select_related("status").all().iterator():
        update_fields = []
        if lead.manager_id in manager_ids and lead.first_manager_id is None:
            lead.first_manager_id = lead.manager_id
            update_fields.append("first_manager_id")
            if lead.first_assigned_at is None:
                lead.first_assigned_at = lead.assigned_at or lead.received_at
                update_fields.append("first_assigned_at")
        if lead.status_id and getattr(lead.status, "conversion_bucket", "IGNORE") == "WON":
            if not lead.sales_closed:
                lead.sales_closed = True
                update_fields.append("sales_closed")
            if lead.won_at is None:
                lead.won_at = lead.updated_at or lead.received_at
                update_fields.append("won_at")
            if lead.won_by_manager_id is None and lead.manager_id in manager_ids:
                lead.won_by_manager_id = lead.manager_id
                update_fields.append("won_by_manager_id")
        if update_fields:
            lead.save(update_fields=update_fields)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_leadauditlog_and_more'),
        ('partners', '0002_alter_partner_id_alter_partnersource_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='first_assigned_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_managed_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='sales_closed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='won_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='won_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadstatus',
            name='conversion_bucket',
            field=models.CharField(choices=[('WON', 'Won'), ('LOST', 'Lost'), ('IGNORE', 'Ignore')], db_index=True, default='IGNORE', max_length=16),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['first_manager', 'first_assigned_at'], name='leads_first_m_91424a_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['won_by_manager', 'won_at'], name='leads_won_by__e036b7_idx'),
        ),
        migrations.RunPython(_backfill_conversion_and_sales, migrations.RunPython.noop),
    ]
