# Generated by Codex on 2026-02-18

from django.db import migrations


def _backfill_first_manager_any_assignee(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")

    for lead in Lead.objects.all().iterator():
        update_fields = []

        if lead.first_manager_id is None:
            if lead.manager_id is not None:
                lead.first_manager_id = lead.manager_id
                update_fields.append("first_manager_id")
            elif lead.won_by_manager_id is not None:
                lead.first_manager_id = lead.won_by_manager_id
                update_fields.append("first_manager_id")

        if lead.first_manager_id is not None and lead.first_assigned_at is None:
            lead.first_assigned_at = lead.assigned_at or lead.received_at
            update_fields.append("first_assigned_at")

        if lead.sales_closed and lead.won_by_manager_id is None and lead.manager_id is not None:
            lead.won_by_manager_id = lead.manager_id
            update_fields.append("won_by_manager_id")

        if update_fields:
            lead.save(update_fields=update_fields)


class Migration(migrations.Migration):
    dependencies = [
        ("leads", "0015_lead_first_assigned_at_lead_first_manager_and_more"),
    ]

    operations = [
        migrations.RunPython(_backfill_first_manager_any_assignee, migrations.RunPython.noop),
    ]

