# Generated by Django 6.0.1 on 2026-02-19 08:48

from django.db import migrations, models


def _backfill_is_valid(apps, schema_editor):
    LeadStatus = apps.get_model("leads", "LeadStatus")
    LeadStatus.objects.filter(conversion_bucket__in=["WON", "LOST"]).update(is_valid=True)
    LeadStatus.objects.filter(conversion_bucket="IGNORE", is_terminal=True, counts_for_conversion=True).update(is_valid=True)
    LeadStatus.objects.filter(conversion_bucket="IGNORE", is_terminal=True, counts_for_conversion=False).update(is_valid=True)


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_backfill_first_manager_any_assignee'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='is_valid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.RunPython(_backfill_is_valid, migrations.RunPython.noop),
    ]
