# Generated by Django 6.0.1 on 2026-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_leadstatus_is_valid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='counts_for_conversion',
        ),
    ]
