# Generated by Django 6.0.1 on 2026-02-19 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def _backfill_stage_outcomes(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    LeadStatus = apps.get_model("leads", "LeadStatus")

    won_status_ids = list(
        LeadStatus.objects.filter(conversion_bucket="WON").values_list("id", flat=True)
    )
    lost_status_ids = list(
        LeadStatus.objects.filter(conversion_bucket="LOST").values_list("id", flat=True)
    )

    Lead.objects.filter(manager_outcome="PENDING", sales_closed=True).update(manager_outcome="WON")
    Lead.objects.filter(manager_outcome="PENDING", won_at__isnull=False).update(manager_outcome="WON")
    if won_status_ids:
        Lead.objects.filter(manager_outcome="PENDING", status_id__in=won_status_ids).update(manager_outcome="WON")
    if lost_status_ids:
        Lead.objects.filter(manager_outcome="PENDING", status_id__in=lost_status_ids).update(manager_outcome="LOST")

    Lead.objects.filter(manager_outcome="WON", manager_outcome_at__isnull=True, won_at__isnull=False).update(
        manager_outcome_at=models.F("won_at")
    )
    Lead.objects.filter(manager_outcome="WON", manager_outcome_by_id__isnull=True, won_by_manager_id__isnull=False).update(
        manager_outcome_by_id=models.F("won_by_manager_id")
    )
    Lead.objects.filter(
        manager_outcome="WON",
        manager_outcome_at__isnull=True,
        assigned_at__isnull=False,
    ).update(manager_outcome_at=models.F("assigned_at"))

    Lead.objects.filter(
        manager_outcome="WON",
        transferred_to_ret_at__isnull=True,
        manager__role="RET",
        assigned_at__isnull=False,
    ).update(transferred_to_ret_at=models.F("assigned_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_remove_leadstatus_counts_for_conversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='manager_outcome',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WON', 'Won'), ('LOST', 'Lost')], db_index=True, default='PENDING', max_length=16),
        ),
        migrations.AddField(
            model_name='lead',
            name='manager_outcome_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='manager_outcome_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_outcome_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='transferred_to_ret_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(_backfill_stage_outcomes, migrations.RunPython.noop),
    ]
