# Generated by Django 6.0.1 on 2026-02-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_manager_outcome_lead_manager_outcome_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_won_by__e036b7_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='sales_closed',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='won_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='won_by_manager',
        ),
    ]
