# Generated by Django 6.0.1 on 2026-02-19 11:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_remove_lead_leads_won_by__e036b7_idx_and_more'),
        ('partners', '0002_alter_partner_id_alter_partnersource_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='lead',
            name='uniq_partner_external_id_notnull',
        ),
        migrations.RemoveIndex(
            model_name='lead',
            name='leads_partner_558987_idx',
        ),
        migrations.AddConstraint(
            model_name='lead',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('phone', ''), _negated=True)), fields=('phone',), name='uniq_lead_phone_alive_nonempty'),
        ),
        migrations.RemoveField(
            model_name='lead',
            name='external_id',
        ),
    ]
