# Generated by Django 6.0.1 on 2026-02-19 12:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_remove_lead_uniq_partner_external_id_notnull_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadauditlog',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_soft_deleted', 'Lead Soft Deleted'), ('lead_restored', 'Lead Restored'), ('lead_hard_deleted', 'Lead Hard Deleted'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_soft_deleted', 'Comment Soft Deleted'), ('comment_restored', 'Comment Restored'), ('comment_pinned', 'Comment Pinned'), ('comment_unpinned', 'Comment Unpinned'), ('duplicate_rejected', 'Duplicate Rejected'), ('deposit_created', 'Deposit Created'), ('deposit_reversed', 'Deposit Reversed'), ('ret_transferred', 'Transferred To RET'), ('ret_transfer_rollback', 'RET Transfer Rollback')], max_length=64),
        ),
        migrations.CreateModel(
            name='LeadDeposit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'FTD'), (2, 'Reload'), (3, 'Deposit')], db_index=True, default=3)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lead_deposits', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', to='leads.lead')),
            ],
            options={
                'db_table': 'lead_deposits',
                'indexes': [models.Index(fields=['lead', 'created_at'], name='lead_deposi_lead_id_3d5e41_idx'), models.Index(fields=['creator', 'created_at'], name='lead_deposi_creator_e44a70_idx'), models.Index(fields=['type', 'created_at'], name='lead_deposi_type_16de1b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('type', 1)), fields=('lead',), name='uniq_lead_ftd_alive'), models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('type', 2)), fields=('lead',), name='uniq_lead_reload_alive')],
            },
        ),
        migrations.CreateModel(
            name='LeadRetTransfer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transferred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('rolled_back_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('rollback_reason', models.TextField(blank=True, default='')),
                ('from_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_transfers_from', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ret_transfers', to='leads.lead')),
                ('rolled_back_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_transfers_rolled_back', to=settings.AUTH_USER_MODEL)),
                ('to_ret', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_transfers_to', to=settings.AUTH_USER_MODEL)),
                ('transferred_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ret_transfers_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_ret_transfers',
                'indexes': [models.Index(fields=['lead', 'is_active'], name='lead_ret_tr_lead_id_bbda5b_idx'), models.Index(fields=['transferred_at'], name='lead_ret_tr_transfe_8db7ff_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_deleted', False)), fields=('lead',), name='uniq_active_ret_transfer_per_lead')],
            },
        ),
    ]
