# Generated by Django 6.0.1 on 2026-02-19 14:28

from django.db import migrations, models


def _normalize_status_codes_and_default(apps, schema_editor):
    LeadStatus = apps.get_model('leads', 'LeadStatus')
    db_alias = schema_editor.connection.alias

    used_codes: set[str] = set()
    alive_statuses = (
        LeadStatus.objects.using(db_alias)
        .filter(is_deleted=False)
        .order_by('code', 'order', 'id')
    )
    for status in alive_statuses:
        base = (status.code or '').strip() or 'status'
        candidate = base[:64]
        if candidate in used_codes:
            suffix = f"_{status.id}"
            candidate = f"{base[: max(1, 64 - len(suffix))]}{suffix}"
        if status.code != candidate:
            status.code = candidate
            status.save(update_fields=['code'])
        used_codes.add(candidate)

    default_ids = list(
        LeadStatus.objects.using(db_alias)
        .filter(is_deleted=False, is_default_for_new_leads=True)
        .order_by('order', 'id')
        .values_list('id', flat=True)
    )
    if len(default_ids) > 1:
        keep_id = default_ids[0]
        (
            LeadStatus.objects.using(db_alias)
            .filter(is_deleted=False, is_default_for_new_leads=True)
            .exclude(id=keep_id)
            .update(is_default_for_new_leads=False)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0022_alter_leadauditlog_event_type_leaddeposit_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='leadstatustransition',
            name='lead_status_pipelin_77d18b_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadstatustransition',
            name='lead_status_from_st_ae23a0_idx',
        ),
        migrations.RemoveConstraint(
            model_name='leadstatustransition',
            name='uniq_status_transition_alive',
        ),
        migrations.RemoveConstraint(
            model_name='leadstatustransition',
            name='check_transition_not_self',
        ),
        migrations.RemoveIndex(
            model_name='pipeline',
            name='lead_pipeli_is_defa_29d7b1_idx',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='pipeline',
        ),
        migrations.RemoveConstraint(
            model_name='leadstatus',
            name='uniq_status_code_per_pipeline_alive',
        ),
        migrations.RemoveConstraint(
            model_name='leadstatus',
            name='uniq_default_status_per_pipeline_alive',
        ),
        migrations.RemoveIndex(
            model_name='leadstatus',
            name='lead_status_pipelin_d5c8e5_idx',
        ),
        migrations.RemoveIndex(
            model_name='leadstatus',
            name='lead_status_pipelin_999135_idx',
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['order'], name='lead_status_order_36820a_idx'),
        ),
        migrations.AddIndex(
            model_name='leadstatus',
            index=models.Index(fields=['is_active'], name='lead_status_is_acti_e1adfb_idx'),
        ),
        migrations.RunPython(
            _normalize_status_codes_and_default,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('code',), name='uniq_status_code_alive'),
        ),
        migrations.AddConstraint(
            model_name='leadstatus',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default_for_new_leads', True), ('is_deleted', False)), fields=('is_default_for_new_leads',), name='uniq_default_status_alive'),
        ),
        migrations.RemoveField(
            model_name='leadstatus',
            name='pipeline',
        ),
        migrations.DeleteModel(
            name='LeadStatusTransition',
        ),
        migrations.DeleteModel(
            name='Pipeline',
        ),
    ]
