# Generated by Django 6.0.1 on 2026-02-20 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_remove_leadstatustransition_lead_status_pipelin_77d18b_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='transferred_to_ret_at',
        ),
    ]
