# Generated by Django 6.0.1 on 2026-02-21 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0025_delete_leadrettransfer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='manager_outcome',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='manager_outcome_at',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='manager_outcome_by',
        ),
    ]
