# Generated by Django 6.0.1 on 2026-02-21 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_remove_lead_manager_outcome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadstatus',
            name='is_terminal',
        ),
    ]
