# Generated by Django 6.0.1 on 2026-02-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0027_remove_leadstatus_is_terminal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(10, 'Low'), (20, 'Normal'), (30, 'High'), (40, 'Urgent')], default=20, null=True),
        ),
    ]
