# Generated by Django 6.0.1 on 2026-02-25 10:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0028_alter_lead_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)]),
        ),
    ]
