# Generated by Django 6.0.1 on 2026-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0029_lead_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
