# Generated by Django 6.0.1 on 2026-02-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0030_alter_lead_custom_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadauditlog',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('lead_status', 'Lead Status'), ('lead_comment', 'Lead Comment'), ('lead_deposit', 'Lead Deposit'), ('duplicate_attempt', 'Duplicate Attempt')], default='lead', max_length=32),
        ),
        migrations.AlterField(
            model_name='leadauditlog',
            name='event_type',
            field=models.CharField(choices=[('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_soft_deleted', 'Lead Soft Deleted'), ('lead_restored', 'Lead Restored'), ('lead_hard_deleted', 'Lead Hard Deleted'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_soft_deleted', 'Comment Soft Deleted'), ('comment_restored', 'Comment Restored'), ('comment_pinned', 'Comment Pinned'), ('comment_unpinned', 'Comment Unpinned'), ('duplicate_rejected', 'Duplicate Rejected'), ('deposit_created', 'Deposit Created'), ('deposit_updated', 'Deposit Updated'), ('deposit_reversed', 'Deposit Reversed'), ('deposit_soft_deleted', 'Deposit Soft Deleted'), ('deposit_restored', 'Deposit Restored'), ('deposit_hard_deleted', 'Deposit Hard Deleted'), ('ret_transferred', 'Transferred To RET'), ('ret_transfer_rollback', 'RET Transfer Rollback')], max_length=64),
        ),
    ]
