# Generated by Django 6.0.1 on 2026-02-28 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0031_alter_leadauditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaddeposit',
            options={'ordering': ('-created_at', '-id')},
        ),
    ]
