# Generated by Django 6.0.1 on 2026-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0032_alter_leaddeposit_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadstatus',
            name='work_bucket',
            field=models.CharField(choices=[('WORKING', 'Working'), ('RETURN', 'Return'), ('NON_WORKING', 'Non-working')], db_index=True, default='WORKING', max_length=16),
        ),
    ]
