# Generated by Django 6.0.1 on 2026-03-03 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0033_leadstatus_work_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadauditlog',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('lead_tag', 'Lead Tag'), ('lead_status', 'Lead Status'), ('lead_comment', 'Lead Comment'), ('lead_deposit', 'Lead Deposit'), ('duplicate_attempt', 'Duplicate Attempt')], default='lead', max_length=32),
        ),
        migrations.AlterField(
            model_name='leadauditlog',
            name='event_type',
            field=models.CharField(choices=[('tag_created', 'Tag Created'), ('tag_updated', 'Tag Updated'), ('tag_soft_deleted', 'Tag Soft Deleted'), ('tag_restored', 'Tag Restored'), ('tag_hard_deleted', 'Tag Hard Deleted'), ('lead_tags_changed', 'Lead Tags Changed'), ('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned'), ('first_manager_changed', 'First Manager Changed'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_soft_deleted', 'Lead Soft Deleted'), ('lead_restored', 'Lead Restored'), ('lead_hard_deleted', 'Lead Hard Deleted'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_soft_deleted', 'Comment Soft Deleted'), ('comment_restored', 'Comment Restored'), ('comment_pinned', 'Comment Pinned'), ('comment_unpinned', 'Comment Unpinned'), ('duplicate_rejected', 'Duplicate Rejected'), ('deposit_created', 'Deposit Created'), ('deposit_updated', 'Deposit Updated'), ('deposit_soft_deleted', 'Deposit Soft Deleted'), ('deposit_restored', 'Deposit Restored'), ('deposit_hard_deleted', 'Deposit Hard Deleted')], max_length=64),
        ),
        migrations.CreateModel(
            name='LeadTag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('color', models.CharField(blank=True, default='', max_length=32)),
                ('icon', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'lead_tags',
                'indexes': [models.Index(fields=['name'], name='lead_tags_name_77e871_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='uniq_lead_tag_name_alive')],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='leads', to='leads.leadtag'),
        ),
    ]
