# Generated by Django 6.0.1 on 2026-03-04 12:49

import apps.leads.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0034_alter_leadauditlog_entity_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadauditlog',
            name='entity_type',
            field=models.CharField(choices=[('lead', 'Lead'), ('lead_tag', 'Lead Tag'), ('lead_status', 'Lead Status'), ('lead_comment', 'Lead Comment'), ('lead_attachment', 'Lead Attachment'), ('lead_deposit', 'Lead Deposit'), ('duplicate_attempt', 'Duplicate Attempt')], default='lead', max_length=32),
        ),
        migrations.AlterField(
            model_name='leadauditlog',
            name='event_type',
            field=models.CharField(choices=[('tag_created', 'Tag Created'), ('tag_updated', 'Tag Updated'), ('tag_soft_deleted', 'Tag Soft Deleted'), ('tag_restored', 'Tag Restored'), ('tag_hard_deleted', 'Tag Hard Deleted'), ('lead_tags_changed', 'Lead Tags Changed'), ('status_changed', 'Status Changed'), ('status_created', 'Status Created'), ('status_updated', 'Status Updated'), ('status_deleted_soft', 'Status Soft Deleted'), ('status_deleted_hard', 'Status Hard Deleted'), ('manager_assigned', 'Manager Assigned'), ('manager_reassigned', 'Manager Reassigned'), ('manager_unassigned', 'Manager Unassigned'), ('first_manager_changed', 'First Manager Changed'), ('lead_created', 'Lead Created'), ('lead_updated', 'Lead Updated'), ('lead_soft_deleted', 'Lead Soft Deleted'), ('lead_restored', 'Lead Restored'), ('lead_hard_deleted', 'Lead Hard Deleted'), ('comment_created', 'Comment Created'), ('comment_updated', 'Comment Updated'), ('comment_soft_deleted', 'Comment Soft Deleted'), ('comment_restored', 'Comment Restored'), ('comment_pinned', 'Comment Pinned'), ('comment_unpinned', 'Comment Unpinned'), ('attachment_created', 'Attachment Created'), ('attachment_soft_deleted', 'Attachment Soft Deleted'), ('attachment_restored', 'Attachment Restored'), ('attachment_hard_deleted', 'Attachment Hard Deleted'), ('duplicate_rejected', 'Duplicate Rejected'), ('deposit_created', 'Deposit Created'), ('deposit_updated', 'Deposit Updated'), ('deposit_soft_deleted', 'Deposit Soft Deleted'), ('deposit_restored', 'Deposit Restored'), ('deposit_hard_deleted', 'Deposit Hard Deleted')], max_length=64),
        ),
        migrations.CreateModel(
            name='LeadAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.leads.models.lead_attachment_upload_to)),
                ('kind', models.CharField(choices=[('audio', 'Audio'), ('image', 'Image'), ('document', 'Document'), ('other', 'Other')], db_index=True, default='other', max_length=16)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=255)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attachments', to='leads.lead')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lead_attachments',
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['lead', 'created_at'], name='lead_attach_lead_id_78e9a2_idx'), models.Index(fields=['uploaded_by', 'created_at'], name='lead_attach_uploade_e16514_idx'), models.Index(fields=['kind', 'created_at'], name='lead_attach_kind_281bc0_idx')],
            },
        ),
    ]
