# Generated by Django 6.0.1 on 2026-03-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0035_alter_leadauditlog_entity_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadattachment',
            name='kind',
            field=models.CharField(choices=[('audio', 'Audio'), ('image', 'Image')], db_index=True, default='image', max_length=16),
        ),
    ]
