# Generated by Django 6.0.1 on 2026-03-13 14:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(max_length=64, unique=True)),
                ('enabled_by_default', models.BooleanField(default=True)),
                ('default_repeat_minutes', models.PositiveIntegerField(default=15)),
                ('default_watch_scope', models.CharField(choices=[('own', 'Own'), ('team', 'Team'), ('all', 'All')], default='own', max_length=16)),
                ('apply_to_teamleaders', models.BooleanField(default=False)),
                ('apply_to_admins', models.BooleanField(default=False)),
                ('apply_to_superusers', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'notification_policies',
                'ordering': ['event_type'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, default='')),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='leads.lead')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=32)),
                ('scheduled_for', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('notification', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='notifications.notification')),
            ],
            options={
                'db_table': 'notification_deliveries',
                'ordering': ['scheduled_for', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='started', max_length=32)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='notifications.notificationdelivery')),
            ],
            options={
                'db_table': 'notification_delivery_attempts',
                'ordering': ['delivery_id', 'sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationOutbox',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('aggregate_type', models.CharField(blank=True, default='', max_length=64)),
                ('aggregate_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('processed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_outbox_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_outbox',
                'ordering': ['available_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('enabled', models.BooleanField(blank=True, null=True)),
                ('repeat_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('watch_scope', models.CharField(blank=True, choices=[('own', 'Own'), ('team', 'Team'), ('all', 'All')], max_length=16, null=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_notification_preferences', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
                'ordering': ['event_type', 'user_id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationWatchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('target_role', models.CharField(blank=True, choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('TEAMLEADER', 'Teamleader'), ('RET', 'Ret'), ('MANAGER', 'Manager')], default='', max_length=32)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_notification_targets', to=settings.AUTH_USER_MODEL)),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_watch_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_watch_targets',
                'ordering': ['event_type', 'watcher_id', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', 'created_at'], name='notificatio_recipie_06c470_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'status', 'scheduled_for'], name='notificatio_recipie_e77cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'event_type', 'created_at'], name='notificatio_recipie_745f11_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'scheduled_for'], name='notificatio_status_c0ec27_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'status'], name='notificatio_notific_131b46_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['dedupe_key', 'status'], name='notificatio_dedupe__ef3699_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['delivery', 'sequence'], name='notificatio_deliver_6ae55e_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdeliveryattempt',
            index=models.Index(fields=['status', 'started_at'], name='notificatio_status_c67eac_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdeliveryattempt',
            constraint=models.UniqueConstraint(fields=('delivery', 'sequence'), name='uniq_notification_delivery_attempt_sequence'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['status', 'available_at'], name='notificatio_status_e56244_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationoutbox',
            index=models.Index(fields=['event_type', 'status', 'available_at'], name='notificatio_event_t_cee0d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationoutbox',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='uniq_notification_outbox_dedupe_key_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='notificationpreference',
            constraint=models.UniqueConstraint(fields=('user', 'event_type'), name='uniq_notification_preference_user_event'),
        ),
        migrations.AddIndex(
            model_name='notificationwatchtarget',
            index=models.Index(fields=['watcher', 'event_type'], name='notificatio_watcher_35587b_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwatchtarget',
            index=models.Index(fields=['event_type', 'target_role'], name='notificatio_event_t_956b80_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationwatchtarget',
            index=models.Index(fields=['event_type', 'target_user'], name='notificatio_event_t_c0a58a_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationwatchtarget',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('target_user__isnull', False), ('target_role', '')), models.Q(('target_user__isnull', True), models.Q(('target_role', ''), _negated=True)), _connector='OR'), name='notification_watch_target_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='notificationwatchtarget',
            constraint=models.UniqueConstraint(condition=models.Q(('target_user__isnull', False)), fields=('watcher', 'event_type', 'target_user'), name='uniq_notification_watch_target_user'),
        ),
        migrations.AddConstraint(
            model_name='notificationwatchtarget',
            constraint=models.UniqueConstraint(condition=models.Q(('target_role', ''), _negated=True), fields=('watcher', 'event_type', 'target_role'), name='uniq_notification_watch_target_role'),
        ),
    ]
