# Generated by Django 6.0.1 on 2026-03-11 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationWatchTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('target_role', models.CharField(blank=True, choices=[('SUPERUSER', 'Superuser'), ('ADMIN', 'Admin'), ('TEAMLEADER', 'Teamleader'), ('RET', 'Ret'), ('MANAGER', 'Manager')], default='', max_length=32)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watched_by_notification_targets', to=settings.AUTH_USER_MODEL)),
                ('watcher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_watch_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_watch_targets',
                'ordering': ['event_type', 'watcher_id', 'id'],
                'indexes': [models.Index(fields=['watcher', 'event_type'], name='notificatio_watcher_35587b_idx'), models.Index(fields=['event_type', 'target_role'], name='notificatio_event_t_956b80_idx'), models.Index(fields=['event_type', 'target_user'], name='notificatio_event_t_c0a58a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('target_user__isnull', False), ('target_role', '')), models.Q(('target_user__isnull', True), models.Q(('target_role', ''), _negated=True)), _connector='OR'), name='notification_watch_target_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('target_user__isnull', False)), fields=('watcher', 'event_type', 'target_user'), name='uniq_notification_watch_target_user'), models.UniqueConstraint(condition=models.Q(('target_role', ''), _negated=True), fields=('watcher', 'event_type', 'target_role'), name='uniq_notification_watch_target_role')],
            },
        ),
    ]
