# Generated by Django 6.0.1 on 2026-03-11 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def backfill_notification_deliveries(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    NotificationDelivery = apps.get_model("notifications", "NotificationDelivery")

    existing_notification_ids = set(
        NotificationDelivery.objects.values_list("notification_id", flat=True)
    )
    pending = []
    batch_size = 500

    for notification in Notification.objects.all().iterator(chunk_size=batch_size):
        if notification.id in existing_notification_ids:
            continue
        pending.append(
            NotificationDelivery(
                notification_id=notification.id,
                channel=getattr(notification, "channel", "in_app"),
                status=notification.status,
                scheduled_for=notification.scheduled_for,
                sent_at=notification.sent_at,
                attempts=getattr(notification, "attempts", 0),
                last_error=getattr(notification, "last_error", ""),
                dedupe_key=getattr(notification, "dedupe_key", ""),
                delivery_payload={},
                created_at=notification.created_at,
                updated_at=notification.updated_at,
            )
        )
        if len(pending) >= batch_size:
            NotificationDelivery.objects.bulk_create(pending, batch_size=batch_size)
            pending = []

    if pending:
        NotificationDelivery.objects.bulk_create(pending, batch_size=batch_size)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
        ("notifications", "0002_notificationwatchtarget"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationDelivery",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("channel", models.CharField(choices=[("in_app", "In App")], db_index=True, default="in_app", max_length=32)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=32)),
                ("scheduled_for", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_error", models.TextField(blank=True, default="")),
                ("dedupe_key", models.CharField(blank=True, db_index=True, default="", max_length=255)),
                ("delivery_payload", models.JSONField(blank=True, default=dict)),
                ("notification", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="deliveries", to="core.notification")),
            ],
            options={
                "db_table": "notification_deliveries",
                "ordering": ["scheduled_for", "id"],
                "indexes": [
                    models.Index(fields=["status", "scheduled_for"], name="notificatio_status_c0ec27_idx"),
                    models.Index(fields=["channel", "status", "scheduled_for"], name="notificatio_channel_457991_idx"),
                    models.Index(fields=["notification", "channel"], name="notificatio_notific_31045d_idx"),
                    models.Index(fields=["dedupe_key", "channel"], name="notificatio_dedupe__a1e9ec_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(fields=("notification", "channel"), name="uniq_notification_delivery_notification_channel"),
                ],
            },
        ),
        migrations.RunPython(backfill_notification_deliveries, migrations.RunPython.noop),
    ]
