# Generated by Django 6.0.1 on 2026-03-11 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notificationdelivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDeliveryAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In App')], db_index=True, default='in_app', max_length=32)),
                ('sequence', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='started', max_length=32)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_logs', to='notifications.notificationdelivery')),
            ],
            options={
                'db_table': 'notification_delivery_attempts',
                'ordering': ['delivery_id', 'sequence', 'id'],
                'indexes': [models.Index(fields=['delivery', 'sequence'], name='notificatio_deliver_6ae55e_idx'), models.Index(fields=['status', 'started_at'], name='notificatio_status_c67eac_idx'), models.Index(fields=['channel', 'status', 'started_at'], name='notificatio_channel_6d4364_idx')],
                'constraints': [models.UniqueConstraint(fields=('delivery', 'sequence'), name='uniq_notification_delivery_attempt_sequence')],
            },
        ),
    ]
