# Generated by Django 6.0.1 on 2026-03-11 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notificationpreference_options_and_more'),
        ('notifications', '0004_notificationdeliveryattempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdelivery',
            name='uniq_notification_delivery_notification_channel',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_channel_457991_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_notific_31045d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_dedupe__a1e9ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdeliveryattempt',
            name='notificatio_channel_6d4364_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX IF NOT EXISTS "
                        "uniq_notification_delivery_notification "
                        "ON notification_deliveries (notification_id)"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS uniq_notification_delivery_notification"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='notificationdelivery',
                    name='notification',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='delivery',
                        to='core.notification',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'status'], name='notificatio_notific_131b46_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['dedupe_key', 'status'], name='notificatio_dedupe__ef3699_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='notificationdelivery',
                    name='channel',
                ),
                migrations.RemoveField(
                    model_name='notificationdelivery',
                    name='delivery_payload',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='channel',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='provider_message_id',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='response_payload',
                ),
            ],
        ),
    ]
