# Generated by Django 6.0.1 on 2026-03-11 11:51

import django.db.models.deletion
from django.db import migrations, models


def _drop_column_if_exists(schema_editor, *, table_name: str, column_name: str) -> None:
    with schema_editor.connection.cursor() as cursor:
        if schema_editor.connection.vendor == "sqlite":
            existing_columns = {
                row[1]
                for row in cursor.execute(f"PRAGMA table_info({table_name})").fetchall()
            }
            if column_name not in existing_columns:
                return
            indexes = cursor.execute(f"PRAGMA index_list({table_name})").fetchall()
            for index_row in indexes:
                index_name = index_row[1]
                if index_name.startswith("sqlite_autoindex_"):
                    continue
                indexed_columns = {
                    info_row[2]
                    for info_row in cursor.execute(f"PRAGMA index_info({index_name})").fetchall()
                }
                if column_name in indexed_columns:
                    cursor.execute(f"DROP INDEX IF EXISTS {index_name}")
            cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN {column_name}")
            return
        cursor.execute(f"ALTER TABLE {table_name} DROP COLUMN IF EXISTS {column_name} CASCADE")


def drop_legacy_notification_columns(apps, schema_editor):
    _drop_column_if_exists(schema_editor, table_name="notification_deliveries", column_name="channel")
    _drop_column_if_exists(schema_editor, table_name="notification_deliveries", column_name="delivery_payload")
    _drop_column_if_exists(schema_editor, table_name="notification_delivery_attempts", column_name="channel")
    _drop_column_if_exists(schema_editor, table_name="notification_delivery_attempts", column_name="provider_message_id")
    _drop_column_if_exists(schema_editor, table_name="notification_delivery_attempts", column_name="response_payload")


def noop(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notificationpreference_options_and_more'),
        ('notifications', '0004_notificationdeliveryattempt'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationdelivery',
            name='uniq_notification_delivery_notification_channel',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_channel_457991_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_notific_31045d_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdelivery',
            name='notificatio_dedupe__a1e9ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='notificationdeliveryattempt',
            name='notificatio_channel_6d4364_idx',
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql=(
                        "CREATE UNIQUE INDEX IF NOT EXISTS "
                        "uniq_notification_delivery_notification "
                        "ON notification_deliveries (notification_id)"
                    ),
                    reverse_sql=(
                        "DROP INDEX IF EXISTS uniq_notification_delivery_notification"
                    ),
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='notificationdelivery',
                    name='notification',
                    field=models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='delivery',
                        to='core.notification',
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'status'], name='notificatio_notific_131b46_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['dedupe_key', 'status'], name='notificatio_dedupe__ef3699_idx'),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_notification_columns, noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='notificationdelivery',
                    name='channel',
                ),
                migrations.RemoveField(
                    model_name='notificationdelivery',
                    name='delivery_payload',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='channel',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='provider_message_id',
                ),
                migrations.RemoveField(
                    model_name='notificationdeliveryattempt',
                    name='response_payload',
                ),
            ],
        ),
    ]
