# Generated by Django 6.0.1 on 2026-03-11 13:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_notification_channel"),
        ("notifications", "0005_remove_notificationdelivery_uniq_notification_delivery_notification_channel_and_more"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Notification",
                    fields=[
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                        ("id", models.BigAutoField(primary_key=True, serialize=False)),
                        ("event_type", models.CharField(db_index=True, max_length=64)),
                        ("status", models.CharField(choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("cancelled", "Cancelled")], db_index=True, default="pending", max_length=32)),
                        ("scheduled_for", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                        ("sent_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                        ("title", models.CharField(max_length=255)),
                        ("body", models.TextField(blank=True, default="")),
                        ("payload", models.JSONField(blank=True, default=dict)),
                        ("is_read", models.BooleanField(db_index=True, default=False)),
                        ("read_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                        ("actor_user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="triggered_notifications", to=settings.AUTH_USER_MODEL)),
                        ("lead", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="notifications", to="leads.lead")),
                        ("recipient", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notifications", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "notifications",
                        "ordering": ["-created_at", "-id"],
                        "indexes": [
                            models.Index(fields=["recipient", "is_read", "created_at"], name="notificatio_recipie_06c470_idx"),
                            models.Index(fields=["recipient", "status", "scheduled_for"], name="notificatio_recipie_e77cb9_idx"),
                            models.Index(fields=["recipient", "event_type", "created_at"], name="notificatio_recipie_745f11_idx"),
                        ],
                    },
                ),
                migrations.CreateModel(
                    name="NotificationPolicy",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                        ("event_type", models.CharField(max_length=64, unique=True)),
                        ("enabled_by_default", models.BooleanField(default=True)),
                        ("default_repeat_minutes", models.PositiveIntegerField(default=15)),
                        ("default_watch_scope", models.CharField(choices=[("own", "Own"), ("team", "Team"), ("all", "All")], default="own", max_length=16)),
                        ("apply_to_teamleaders", models.BooleanField(default=False)),
                        ("apply_to_admins", models.BooleanField(default=False)),
                        ("apply_to_superusers", models.BooleanField(default=False)),
                    ],
                    options={
                        "db_table": "notification_policies",
                        "ordering": ["event_type"],
                    },
                ),
                migrations.CreateModel(
                    name="NotificationPreference",
                    fields=[
                        ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                        ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                        ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                        ("event_type", models.CharField(db_index=True, max_length=64)),
                        ("enabled", models.BooleanField(blank=True, null=True)),
                        ("repeat_minutes", models.PositiveIntegerField(blank=True, null=True)),
                        ("watch_scope", models.CharField(blank=True, choices=[("own", "Own"), ("team", "Team"), ("all", "All")], max_length=16, null=True)),
                        ("updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="updated_notification_preferences", to=settings.AUTH_USER_MODEL)),
                        ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="notification_preferences", to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        "db_table": "notification_preferences",
                        "ordering": ["event_type", "user_id"],
                    },
                ),
                migrations.AddConstraint(
                    model_name="notificationpreference",
                    constraint=models.UniqueConstraint(fields=("user", "event_type"), name="uniq_notification_preference_user_event"),
                ),
                migrations.AlterField(
                    model_name="notificationdelivery",
                    name="notification",
                    field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="delivery", to="notifications.notification"),
                ),
            ],
        ),
    ]
